[theme]
# Wymuś tryb ciemny dla wszystkich użytkowników
base = "dark"
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
# Dodatkowe ustawienia serwera (opcjonalne)
headless = true